engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "phpcs.xml"
  phpmd:
    enabled: true
    config:
      rulesets: "cleancode,codesize,controversial,design,unusedcode"
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
ratings:
  paths:
  - "lib/**.php"
  - "tests/**.php"
exclude_paths:
- "composer.json"
- "composer.lock"
- "LICENSE"
- "phpcs.xml"
- "pakefile.php"
