engines:
  phpcodesniffer:
    enabled: true
    standard: "phpcs.xml"
  phpmd:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "lib/**.php"
  - "tests/**.php"
exclude_paths:
- "composer.json"
- "composer.lock"
- "LICENSE"
- "phpcs.xml"
- "pakefile.php"
