engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "phpcs.xml"
  phpmd:
    enabled: true
    config:
      rulesets: "cleancode,codesize,controversial,design,unusedcode"
    checks:
      CleanCode/StaticAccess:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "lib/**/*.php"
  - "lib/*.php"
  - "tests/**/*.php"
  - "tests/*.php"
exclude_paths:
- "composer.json"
- "composer.lock"
- "LICENSE"
- "phpcs.xml"
- "pakefile.php"
