language: php
php:
- 5.5
- 5.6
- 7
- hhvm

install:
- rm -r ~/.composer
- composer self-update
- composer install
script:
- vendor/bin/pake $TASK

env:
- TASK="phpunit"

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
  - vendor

branches:
  only:
    - master
