version: 2

build: &BUILD
  steps:
    - run: apk update && apk add git openssh curl build-base autoconf gcc binutils
    - run: echo "date.timezone = Etc/UTC" >> $PHP_INI_DIR/php.ini
    - run: docker-php-ext-install bcmath
    - checkout
    - run: (php --version | head) > php.version
    - run: curl -L -o composer https://getcomposer.org/download/$COMPOSER_VERSION/composer.phar && chmod a+x composer
    - restore_cache:
        key: dependency-cache-<< checksum "php.version" >>-<< checksum "composer.json" >>
        paths:
          - vendor
    - run: ./composer install
    - run: pecl install xdebug-$XDEBUG_VERSION && docker-php-ext-enable xdebug
    - run: php -i
    - save_cache:
        key: dependency-cache-<< checksum "php.version" >>-<< checksum "composer.json" >>
        paths:
          - vendor
    - run: vendor/bin/pake phpcs
    - run: vendor/bin/pake phpunit
    - store_test_results:
        path: build/reports
    - store_artifacts:
        path: build
        destination: build

jobs:
  php56:
    <<: *BUILD
    working_directory: /root/colourist
    environment:
      - COMPOSER_VERSION: 1.4.2
      - PHP_VERSION: 5.6
      - XDEBUG_VERSION: 2.5.5
    docker:
      - image: php:5.6.31-alpine
  php70:
    <<: *BUILD
    working_directory: /root/colourist
    environment:
      - COMPOSER_VERSION: 1.4.2
      - PHP_VERSION: 7.0
      - XDEBUG_VERSION: stable
    docker:
      - image: php:7.0.21-alpine
  php71:
    <<: *BUILD
    working_directory: /root/colourist
    environment:
      - COMPOSER_VERSION: 1.4.2
      - PHP_VERSION: 7.1
      - XDEBUG_VERISON: stable
    docker:
      - image: php:7.1.20-alpine
  php72:
    <<: *BUILD
    working_directory: /root/colourist
    environment:
      - COMPOSER_VERSION: 1.4.2
      - PHP_VERSION: 7.2
      - XDEBUG_VERISON: stable
    docker:
      - image: php:7.2.8-alpine

workflows:
  version: 2
  ci:
    jobs:
      - php56
      - php70
      - php71
      - php72
